name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: MuriloIuryBarbosa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Follow-up of issues and pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories

      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: MuriloIuryBarbosa
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Generate pull requests and issues metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.prs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: MuriloIuryBarbosa
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories